export default function Head() {
  return (
    <>
      <title>Pokedex</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />

      {/* @ts-ignore */}
      <link rel='preconnect' href='https://fonts.googleapis.com' precedence='default'/>
      {/* @ts-ignore */}
      <link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin='true' precedence='default'/>
      {/* @ts-ignore */}
      <link href='https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@200;300&family=Poppins&display=swap' rel='stylesheet' precedence='default' />
    </>
  );
}
